require:
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 2.7
  NewCops: enable
  Exclude:
    - '.pryrc'

Layout/LineLength:
  Max: 120

Layout/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space

Style/Documentation:
  Enabled: false

Layout/DotPosition:
  EnforcedStyle: trailing

Style/EmptyMethod:
  EnforcedStyle: expanded

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Metrics/BlockLength:
  Exclude:
    - spec/**/*

RSpec/MultipleExpectations:
  Enabled: false

RSpec/MessageSpies:
  Enabled: false

RSpec/ContextWording:
  Enabled: false

RSpec/ExampleLength:
  Max: 15

RSpec/NestedGroups:
  Max: 4
