version: '3.3'

services:
  app:
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
    expose:
      - "3000"
    ports:
      - "8081:3000"
    depends_on:
      - storage
    volumes:
      - ..:/app
      - ../../gems:/localgems
      - ssh-data:/ssh:ro
      - bundler-data:/bundle
    networks:
      - default
      - frontend
    command: bundle exec puma -C puma.rb
    environment:
      - BUNDLE_PATH=/bundle/${DOCKER_RUBY_VERSION}
      - SSH_AUTH_SOCK=/ssh/auth/sock
      - VIRTUAL_HOST=files-test.$DOCKER_TLD
      - VIRTUAL_PATH=/
    stdin_open: true
    tty: true

  storage:
    image: atmoz/sftp:alpine
    volumes:
      - ../upload:/home/foo/upload
    command: foo:pass:::upload

volumes:
  bundler-data:
    external:
      name: bundler_data

  ssh-data:
    external:
      name: ssh_data

networks:
  frontend:
    external:
      name: frontend
